export enum RocketsConstants {
  ROCKETS_PENDING = 'ROCKETS_PENDING',
  ROCKETS_REJECTED = 'ROCKETS_REJECTED',
  ROCKETS_FULFILLED = 'ROCKETS_FULFILLED',
  OPEN_FULL_IMAGE_SHOWED = 'OPEN_FULL_IMAGE_SHOWED',
}
